name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - feat/test-ci-cd

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        with:
          ref: feat/test-ci-cd

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Install PM2
        run: npm install pm2

      - name: Grant permisson for pm2.sh
        run: chmod +x ./pm2.sh

      - name: Run pm2.sh
        run: bash ./pm2.sh

      - name: Check pm2 status
        run: pm2 status
